[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
paris = { version = "1.5.15", features = ["macros"] }
image = { version = "0.24.6", features = ["webp-encoder"] }
ravif = "0.11.1"
resvg = "0.32.0"
tar = "0.4.38"
simplelog = "0.12.1"
mtpng = "0.3.5"
rayon = "1.7.0"
