[[include]]
paths = [
    "./emoji/hands/hands.toml",
    "./emoji/smileys/smileys.toml",
    "./emoji/flags/flags.toml",
]

[[include]]
paths = [
    "./reusable.toml",
]

[[include]]
paths = [
    "./targets/containers.toml",
    "./targets/formats.toml",
    "./targets/sizes.toml",
    "./targets/structures.toml",
    "./targets/metadata.toml",
]
