[pack]

[[include]]
paths = [
    "./hands/hands.toml",
    "./smileys/smileys.toml",
]

[[include]]
paths = [
    "./reusable.toml",
]

[[target]]
name = "debug-svg"
tags = [ "debug" ]
include_tags = [ "unicode", "extra" ]
output = { format = "svg" }
structure = { container = "directory", subdirectories = false, filenames = "shortcode" }

[[target]]
name = "unicode-codepoint-png-128"
tags = [ "release" ]
include_tags = [ "unicode" ]
output = { format = "png-oxipng-libdeflater", size = 128, compression = 12.0 }
structure = { container = "tar.gz", subdirectories = false, filenames = "codepoint" }

[[target]]
name = "full-shortcode-webp-512"
tags = [ "release" ]
include_tags = [ "unicode", "extra" ]
output = { format = "webp", size = 512 }
structure = { container = "tar.gz", subdirectories = true, filenames = "shortcode" }

[[target]]
name = "full-metadata"
tags = [ "debug", "metadata" ]
include_tags = [ "unicode", "extra" ]
output = { format = "none" }
structure = { container = "directory", subdirectories = false, filenames = "shortcode" }
