[[include]]
paths = [
    "./emoji/hands/hands.toml",
    "./emoji/smileys/smileys.toml",
]

[[include]]
paths = [
    "./reusable.toml",
]

[[include]]
paths = [
    "./targets/debug.toml",
    "./targets/release.toml",
    "./targets/metadata.toml",
]
