[[target]]
name = "unicode-codepoint-png-128"
tags = [ "release" ]
include_tags = [ "unicode" ]
output = { format = "png-oxipng-libdeflater", size = 128, compression = 12.0 }
structure = { container = "directory", flat = true, filenames = "codepoint" }
include_files = [ "../LICENSE" ]

[[target]]
name = "full-shortcode-webp-512"
tags = [ "release" ]
include_tags = [ "unicode", "extra" ]
output = { format = "webp", size = 512 }
structure = { container = "zip", flat = false, filenames = "shortcode" }
include_files = [ "../LICENSE" ]

[[target]]
name = "full-shortcode-png-32"
tags = [ "release" ]
include_tags = [ "unicode", "extra" ]
output = { format = "png-oxipng-zopfli", size = 32, compression = 14.0 }
structure = { container = "directory", flat = true, filenames = "shortcode" }
include_files = [ "../LICENSE" ]

[[target]]
name = "full-shortcode-avif-64"
tags = [ "release" ]
include_tags = [ "unicode", "extra" ]
output = { format = "avif-lossy", compression = 95.0, size = 64 }
structure = { container = "directory", flat = false, filenames = "shortcode" }
include_files = [ "../LICENSE" ]
