name: Build and release Mutant Remix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-mutant-remix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build for Windows
        uses: mirlahiji/rust-action@master
        with:
          args: cargo build --release --target x86_64-pc-windows-gnu

      - name: Build for Apple
        uses: mirlahiji/rust-action@master
        with:
          args: cargo test --release --target x86_64-apple-darwin

      - name: Build for Linux
        uses: gmiam/rust-musl-action@master
        with:
          args: cargo build --release --target x86_64-unknown-linux-musl

      - name: Move build artifacts
        run: |
          mkdir release
          mv target/x86_64-pc-windows-gnu/release/mrxbuilder.exe release/mrxbuilder-x86_64-windows-gnu-v${{ github.run_number }}.exe
          mv target/x86_64-unknown-linux-musl/release/mrxbuilder release/mrxbuilder-x86_64-linux-musl-v${{ github.run_number }}
          mv target/x86_64-apple-darwin/release/mrxbuilder release/mrxbuilder-x86_64-apple-darwin-v${{ github.run_number }}

      - name: Compress binaries
        run: |
          strip release/*
          # Leaving out the windows binary due to AV false positives
          upx --best --lzma release/mrxbuilder-x86_64-linux-musl-v${{ github.run_number }}
          upx --best --lzma mrxbuilder-x86_64-apple-darwin-v${{ github.run_number }}

      - name: Pack build artifacts
        run: |
          cp -r docs README.md LICENSE release

          tar -czf mrxbuilder-x86_64-linux-musl-v${{ github.run_number }}.tar.gz \
            -C release mrxbuilder-x86_64-linux-musl-v${{ github.run_number }} README.md LICENSE docs
          tar -czf mrxbuilder-x86_64-apple-darwin-v${{ github.run_number }}.tar.gz \
            -C release mrxbuilder-x86_64-apple-darwin-v${{ github.run_number }} README.md LICENSE docs
          zip -r mrxbuilder-x86_64-windows-gnu-v${{ github.run_number }}.zip \
            release/mrxbuilder-x86_64-windows-gnu-v${{ github.run_number }}.exe README.md LICENSE docs

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            mrxbuilder-x86_64-linux-musl-v${{ github.run_number }}.tar.gz
            mrxbuilder-x86_64-apple-darwin-v${{ github.run_number }}.tar.gz
            mrxbuilder-x86_64-windows-gnu-v${{ github.run_number }}.zip

  publish-draft-release:
    needs: build-mutant-remix
    runs-on: ubuntu-latest

    # Only run this job on manual trigger
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Download pack artifact
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: binaries

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            binaries/mrxbuilder-x86_64-linux-musl-v${{ github.run_number }}.tar.gz
            binaries/mrxbuilder-x86_64-apple-darwin-v${{ github.run_number }}.tar.gz
            binaries/mrxbuilder-x86_64-windows-gnu-v${{ github.run_number }}.zip
          tag_name: v${{ github.run_number }}
          name: mrxbuilder v${{ github.run_number }}
          draft: true
