name: Build and release Mutant Remix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-mrxbuilder:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # [ target, name, extension ]
        target: [
          [ "x86_64-pc-windows-gnu", "x86_64-windows", ".exe",],
          # [ "x86_64-apple-darwin", "x86_64-macos", "" ],
          # [ "aarch64-apple-darwin", "arm64-macos", "" ],
          [ "x86_64-unknown-linux-musl", "x86_64-linux-musl", "" ],
          [ "aarch64-unknown-linux-musl", "arm64-linux-musl", "" ],
          [ "x86_64-unknown-linux-gnu", "x86_64-linux-gnu", "" ],
          [ "aarch64-unknown-linux-gnu", "arm64-linux-gnu", "" ],
        ]

    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install build dependencies for windows
        if: matrix.target[0] == 'x86_64-pc-windows-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-mingw-w64-x86-64 \
            binutils-mingw-w64-x86-64 \
            mingw-w64-tools \
            mingw-w64-common \
            mingw-w64-x86-64-dev \
            mingw-w64-i686-dev

      - name: Install build dependencies for musl and aarch64
        if: matrix.target[0] == 'x86_64-unknown-linux-musl' || matrix.target[0] == 'aarch64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            musl-tools \
            musl-dev \
            musl \
            musl-dev \
            musl-tools \
            musl-cross \
            musl-cross-make \
            musl-cross-dev \
            musl-cross-binutils \
            musl-cross-headers \
            musl-cross-x86_64 \
            musl-cross-arm-linux-musleabi \

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target[0] }}
          override: true

      - name: Build for ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target[0] }}

      - name: Prepare directories
        run: |
          mkdir binaries release
          cp -r docs README.md LICENSE binaries

      - name: Copy ${{ matrix.target[0] }} binary
        run: |
          cp target/${{ matrix.target[0] }}/release/${{ matrix.target[1] }}${{ matrix.target[2] }} \
            binaries/mrxbuilder-v${{ github.run_number }}-${{ matrix.target[1] }}${{ matrix.target[2] }}

      - name: Strip debug symbols
        run: strip binaries/mrxbuilder-v${{ github.run_number }}-${{ matrix.target[1] }}${{ matrix.target[2] }}

      - name: Compress ${{ matrix.target[0] }} binary with UPX
        if: matrix.target[0] != 'x86_64-pc-windows-gnu'
        run: upx --best --lzma binaries/mrxbuilder-v${{ github.run_number }}-${{ matrix.target[1] }}${{ matrix.target[2] }}

      - name: Pack ${{ matrix.target[0] }}
        run: |
          tar -cvzf release/mrxbuilder-v${{ github.run_number }}-${{ matrix.target[1] }}.tar.gz \
            -C binaries \
            mrxbuilder-v${{ github.run_number }}-${{ matrix.target[1] }}${{ matrix.target[2] }} \
            docs README.md LICENSE

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release/*

  publish-draft-release:
    needs: build-mrxbuilder
    runs-on: ubuntu-latest

    # Only run this job on manual trigger
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Download pack artifact
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: binaries

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries/*
          tag_name: v${{ github.run_number }}
          name: mrxbuilder v${{ github.run_number }}
          draft: true
