name: Build and release mrxbuilder

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-mrxbuilder:
    strategy:
      matrix:
        target:
          - name: x86_64-windows
            triple: x86_64-pc-windows-gnu
            extension: .exe
            runner: windows-latest

          - name: x86_64-linux-gnu
            triple: x86_64-unknown-linux-gnu
            extension: ""
            runner: ubuntu-latest

          - name: x86_64-macos
            triple: x86_64-apple-darwin
            extension: ""
            runner: macos-latest

    runs-on: ${{ matrix.target.runner }}

    steps:
      - uses: actions/checkout@v3

      - name: Install nasm
        uses: ilammy/setup-nasm@v1

      - name: Build binary
        run: cargo build --profile ci --target ${{ matrix.target.triple }}

      - name: Get version from Cargo.toml
        id: get_version
        run: echo ::set-output name=version::$(cargo metadata --format-version 1 | jq -r '.packages[0].version')

      - name: Copy binary
        run: |
          cp target/${{ matrix.target.triple }}/ci/mrxbuilder${{ matrix.target.extension }} mrxbuilder-v${{ steps.get_version.outputs.version }}-${{ matrix.target.name }}${{ matrix.target.extension }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target.name }}
          path: mrxbuilder-v${{ steps.get_version.outputs.version }}-${{ matrix.target.name }}${{ matrix.target.extension }}

  publish-draft-release:
    needs: build-mrxbuilder
    runs-on: ubuntu-latest

    # Only run this job on manual trigger
    if: github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v3

      - name: Download built binaries
        uses: actions/download-artifact@v3
        with:
          path: binaries

      - name: Get version from Cargo.toml
        id: get_version
        run: echo ::set-output name=version::$(cargo metadata --format-version 1 | jq -r '.packages[0].version')

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries/**/*
          tag_name: v${{ steps.get_version.outputs.version }}
          name: mrxbuilder v${{ steps.get_version.outputs.version }}
          draft: true
