name: Build and release Mutant Remix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-mrxbuilder:
    strategy:
      matrix:
        target:
          - name: x86_64-windows
            triple: x86_64-pc-windows-gnu
            extension: .exe
            runner: windows-latest

          - name: x86_64-linux-musl
            triple: x86_64-unknown-linux-musl
            extension: ""
            runner: ubuntu-latest

          - name: x86_64-linux-gnu
            triple: x86_64-unknown-linux-gnu
            extension: ""
            runner: ubuntu-latest

          - name: arm64-linux-musl
            triple: aarch64-unknown-linux-musl
            extension: ""
            runner: ubuntu-latest

          - name: arm64-linux-gnu
            triple: aarch64-unknown-linux-gnu
            extension: ""
            runner: ubuntu-latest

          - name: x86_64-macos
            triple: x86_64-apple-darwin
            extension: ""
            runner: macos-latest

          - name: arm64-macos
            triple: aarch64-apple-darwin
            extension: ""
            runner: macos-latest

    runs-on: ${{ matrix.target.runner }}

    steps:
      - uses: actions/checkout@v3

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.target.triple }}
          args: "--locked --release"
          strip: true

      - name: Move binary
        run: |
          cp target/${{ matrix.target.triple }}/release/mrxbuilder${{ matrix.target.extension }} \
            mrxbuilder-v${{ github.run_number }}-${{ matrix.target.name }}${{ matrix.target.extension }}

      - name: Compress ${{ matrix.target.name }} binary with UPX
        # Leaving out Windows due to AV false positives
        if: matrix.target.triple != 'x86_64-pc-windows-gnu'
        run: upx --best --lzma mrxbuilder-v${{ github.run_number }}-${{ matrix.target.name }}${{ matrix.target.extension }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target.name }}
          path: mrxbuilder-v${{ github.run_number }}-${{ matrix.target.name }}${{ matrix.target.extension }}

  publish-draft-release:
    needs: build-mrxbuilder
    runs-on: ubuntu-latest

    # Only run this job on manual trigger
    if: github.event_name == 'workflow_dispatch'


    steps:
      - uses: actions/checkout@v3

      - name: Download x86_64-windows artifact
        uses: actions/download-artifact@v2
        with:
          name: x86_64-windows
          path: release

      - name: Download x86_64-linux-musl artifact
        uses: actions/download-artifact@v2
        with:
          name: x86_64-linux-musl
          path: release

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries/*
          tag_name: v${{ github.run_number }}
          name: mrxbuilder v${{ github.run_number }}
          draft: true
